package net.ltxprogrammer.changed.client;

import com.google.common.collect.ImmutableList;
import net.minecraft.client.model.geom.builders.CubeDefinition;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.UVPair;
import net.minecraft.core.Direction;
import org.joml.Vector3f;

import javax.annotation.Nullable;
import java.util.List;
import java.util.Set;

public interface CubeListBuilderExtender {
    /**
     * Discards faces that would be generated by the last submitted cube.
     * @param directions Faces to remove. Note: Directions are based on orientation in BlockBench, not vanilla.
     *                   Vanilla models are upside down, so this function treats DOWN as UP and UP as DOWN.
     * @return this
     */
    CubeListBuilderExtender removeLastFaces(Direction... directions);

    /**
     * Copies the UV from one face of the last submitted cube to another.
     * @deprecated Use {@link #overrideLastFaceTexOffs overrideLastFaceTexOffs()}
     * @param from Face to copy UV from
     * @param to Face to copy UV to
     * @return this
     */
    @Deprecated
    CubeListBuilderExtender copyLastFaceUVStart(Direction from, Direction to);

    /**
     * Overrides the default UV placement on a given face on the last submitted cube. Texture
     * @param face Face to override the texture coordinates of. Note: Directions are based on orientation in BlockBench, not vanilla.
     *             Vanilla models are upside down, so this function treats DOWN as UP and UP as DOWN.
     * @param xOffset X component of the top left point of the texture the face should use
     * @param yOffset Y component of the top left point of the texture the face should use
     * @return this
     */
    CubeListBuilderExtender overrideLastFaceTexOffs(Direction face, int xOffset, int yOffset);
    CubeListBuilder finish();

    void addTriangle(String comment, Vector3f p1, UVPair uv1,
                     Vector3f p2, UVPair uv2,
                     Vector3f p3, UVPair uv3);

    default void addTriangle(String comment, Vector3f p1, float u1, float v1,
                     Vector3f p2, float u2, float v2,
                     Vector3f p3, float u3, float v3) {
        addTriangle(comment, p1, new UVPair(u1, v1), p2, new UVPair(u2, v2), p3, new UVPair(u3, v3));
    }

    default void addTriangle(String comment, float x1, float y1, float z1, float u1, float v1,
                     float x2, float y2, float z2, float u2, float v2,
                     float x3, float y3, float z3, float u3, float v3) {
        addTriangle(comment, new Vector3f(x1, y1, z1), u1, v1, new Vector3f(x2, y2, z2), u2, v2, new Vector3f(x3, y3, z3), u3, v3);
    }

    default void addTriangle(float x1, float y1, float z1, float u1, float v1,
                     float x2, float y2, float z2, float u2, float v2,
                     float x3, float y3, float z3, float u3, float v3) {
        addTriangle(null, x1, y1, z1, u1, v1, x2, y2, z2, u2, v2, x3, y3, z3, u3, v3);
    }

    @Nullable
    List<Triangle.Definition> getTriangles();

    CubeListBuilderExtender texOffs(int xTexOffs, int yTexOffs);
    CubeListBuilderExtender mirror();
    CubeListBuilderExtender mirror(boolean mirror);

    CubeListBuilderExtender addBox(String comment, float x, float y, float z, int width, int height, int depth, CubeDeformation deformation, int xTexOffs, int yTexOffs);
    CubeListBuilderExtender addBox(String comment, float x, float y, float z, int width, int height, int depth, int xTexOffs, int yTexOffs);
    CubeListBuilderExtender addBox(float x, float y, float z, float width, float height, float depth);
    CubeListBuilderExtender addBox(float x, float y, float z, float width, float height, float depth, Set<Direction> visibleFaces);
    CubeListBuilderExtender addBox(String comment, float x, float y, float z, float width, float height, float depth);
    CubeListBuilderExtender addBox(String comment, float x, float y, float z, float width, float height, float depth, CubeDeformation deformation);
    CubeListBuilderExtender addBox(float x, float y, float z, float width, float height, float depth, boolean mirror);
    CubeListBuilderExtender addBox(float x, float y, float z, float width, float height, float depth, CubeDeformation deformation, float texScaleX, float texScaleY);
    CubeListBuilderExtender addBox(float x, float y, float z, float width, float height, float depth, CubeDeformation deformation);

    List<CubeDefinition> getCubes();
}
